### ISSUE TITLE
[AGE System] Focus bonuses on Character page not applied

### ISSUE THREAD

**Issue by caderaspindrift** [Roll20/roll20-character-sheets#8897] opened 2021-05-16 01:43 UTC
Focus bonuses are not consistently applied when focus rolls are made from the Character page.

Focus bonuses are consistently applied when the focus rolls are made from the Focuses page.

The latter behavior is the correct one. Focus bonuses should be applied from the character page.

**Comment by nmbradley** [comment] 2021-06-04 17:35
@caderaspindrift did you resolve this yourself with #8895 ?

**Comment by vkdolea** [comment] 2021-06-09 11:17
#8897 was opened because PR #8895 didn't solve the Focus issue. This was stated on Green Ronin Discord by @caderaspindrift.

**Comment by the-Dissilent** [comment] 2021-12-21 05:26
The problem is that when the default value is used, the character tab was assuming 0, instead of the default 2 set by the Focus tab. In order to fix this, change:
`<input type="hidden" name="attr_focusbonus">`
to
`<input type="hidden" name="attr_focusbonus" value='2'>`
under each attribute in the Character tab

**Comment by the-Dissilent** [comment] 2021-12-27 15:33
My pull-request got approved, and merged into the master.
This bug is now fixed, and the focus bonuses apply to both the Focus tab and the Character tab.

**Closed** 2022-02-08 03:06 UTC
