### ISSUE TITLE
[Shadowrun5thEdition] Fake ID name is not selectable with the mouse

### ISSUE THREAD

**Issue by krakjen** [Roll20/roll20-character-sheets#6136] opened 2020-04-09 14:03 UTC
When you edit/create a Fake ID, the box for the fake name can't be clicked in to input text.

Workaround: 
You can click in the following text box (lifestyles), then shift-tab into the name box.

![image](https://user-images.githubusercontent.com/54226388/78903424-64dd1d00-7a7b-11ea-8c07-f56669388bb4.png)

**Comment by krakjen** [comment] 2020-04-09 14:06
@clevett Also, I didn't want to make a separate bug issue about this, since it's pretty minor ( I didn't find any related issue in the actual sheet), but there is still one occurrence of "eletronicwarfare" in Shadowrun5thEdition.html, line 2953.

**Comment by krakjen** [comment] 2020-04-09 22:19
Alright, sorry to bother you again, but I don't know if this is a bug or intended behaviour/system limitation.
The Damage Monitor of a character with High Pain Tolerance is unchanged. The effect is correctly applied on the dicerolls but the Wound Modifier is not shifted on the Monitor.
Is this normal?

Here is an example of what one could expect for a character with HPT rating 2:
![image](https://user-images.githubusercontent.com/54226388/78945581-fa4ed000-7ac0-11ea-9045-113dfec7726b.png)

**Comment by clevett** [comment] 2020-04-09 22:42
There is no functionality to move the numbers. It just applies the effects. I'll think about that one.

**Comment by krakjen** [comment] 2020-04-09 22:51
Alright, so not a bug then :)
Cheers

**Comment by clevett** [comment] 2020-04-10 01:29
Thanks for the screenshots. That was helpful for finding the issues. I have fixed e-ward & social bug.

The negative numbers is not a bug but I'll put it on my todo list. I'll need to refactor that section to do it and so it will be a bit of a project. Something for the future.

**Comment by krakjen** [comment] 2020-04-10 08:20
Glad I could help. You are doing tremendous work with this project.

**Comment by clevett** [comment] 2020-04-14 20:03
Going to close this issue as it should be fixed **tomorrow** when the code goes live. If its not let me know and I'll reopen it.

**Closed by clevett** 2020-04-14 20:03 UTC

**Comment by krakjen** [comment] 2020-04-15 16:29
Tested it and it's all good now. Good job.
