### ISSUE TITLE
Blades in the Dark Sheet V3.5/Chrome: images broken

### ISSUE THREAD

**Issue by delwaterman** [Roll20/roll20-character-sheets#3788] opened 2018-05-22 17:13 UTC
Original issue: https://github.com/joesinghaus/Blades-in-the-Dark/issues/3

<img width="327" alt="screen shot 2018-05-22 at 1 11 45 pm" src="https://user-images.githubusercontent.com/70605/40378579-f6f408bc-5dc1-11e8-8deb-efbd4ed438fe.png">

**Comment by joesinghaus** [comment] 2018-05-22 18:12
duplicate of #3787.

**Comment by joesinghaus** [comment] 2018-05-27 10:33
I hope you were able to resolve your browser problems. You should probably delete this and #3787 so that they no longer clog up the issue tracker.

**Comment by Anduh** [comment] 2018-07-17 12:02
Yeah resolved issues could be closed

**Closed** 2018-07-31 16:29 UTC
