### ISSUE TITLE
Dark Heresy 2E Characteristic Rolls (Character Sheet)

### ISSUE THREAD

**Issue by Walterros** [Roll20/roll20-character-sheets#2147] opened 2017-01-09 19:39 UTC
In the character sheet for Dark Heresy 2E, the drop down menu used to denote whether PCs have purchased a +5, +10, +15 ect advance is not factored into characteristic rolls OR skill rols For example, if an individual with 50 Weapon Skill has purchased a +5 advance and uses the drop down menu to note such, when they click to roll it'll only do 50+0 instead of 50+5. Likewise, if they perform a parry check (based off weapon skill) it'll generate 50 - 20 (lack of parry skill) +0 instead of 50 - 20 + 10. The only area where the addition is taken into account is if rolling to hit with a weapon, then it'll generate 50 + 10.

Hope that makes sense!

**Comment by RhOmicron** [comment] 2017-01-11 21:24
I could take a look at this and see if I can fix this. If there are any other takers I'll check back.

**Comment by RandomnessUK** [comment] 2017-01-11 21:46
Hi omicron,

I have the  code to pick up on attribute advances from those chosen in thr sheet. After consulting with other players and gms I decided not to include it as players are used to using it to track increased exp costs rather than avoid adding the +5 manually. In addition it makes it harder to see the target for rolls as the  attribute may be 40 but have a +25. You then need to remember that a roll st 0 had a 65 target. Calculating the advance once is easier than calculating it mentally every time you roll.

**Comment by RhOmicron** [comment] 2017-01-11 21:52
Im not too familiar with the rules but what would happen if I added a box under it that look the same where they can track the increased xp cost?

**Comment by RandomnessUK** [comment] 2017-01-11 22:11
The xp cost is based on an attribute called "aptitude" and how many
advances you have taken. The box wouldn't directly help

On 11 Jan 2017 21:52, "RhOmicron" <notifications@github.com> wrote:

Im not too familiar with the rules but what would happen if I added a box
under it that look the same where they can track the increased xp cost?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Roll20/roll20-character-sheets/issues/2147#issuecomment-272007036>,
or mute the thread

**Comment by RhOmicron** [comment] 2017-01-11 22:13
So why do they use the one thats there to track it? If you have two boxes they can track it and the rolls are calculated properly. Unless there is a better thing you can add for the xp cost.

**Comment by RandomnessUK** [comment] 2017-01-11 23:31
Ok so the box for the + to characteristics is a redundant carry over from the character sheets that come with the core rulebook. They existed in the first iteration to log how many advances you have taken on a characteristic, for example the xp cost to advance strength (based on having both aptitudes for it) is 100xp for the first +5, 250xp for the next, 500xp for the next and so on.
However, as aptitudes are different for different characters the cost to advance characteristics are not linear.  The individual player has to be aware of their aptitudes and the cost to advance them will change both based on how many characteristic advances you have taken as well as whether you have two aptitudes, one aptitude or none.

In the 40k rpg system it utilises a d100 to roll, if you roll lower than the characteristic you succeed. Therefore a strength of 60 gives you a 60% chance to succeed on a strength test before adjusting for modifiers.

In my opinion, and the opinion of my players and other gms I've discussed this with, it is more trouble than it is worth to make the strength attribute to pick up on characteristic advances to roll within the sheet.  The main reason for this is that if you have a 50 strength attribute and +10 in advances when you look at your character sheet you will (as a player or gm) have to take the strength attribute, add the +10 in your head and then deduct the (for example) 30 in your head if the gm gives you a very hard test.  This is the only way you can know that you have a 30% chance to succeed before you try the test.

So either you manually input the +10 once and see 60 as your characteristic, or you mentally calculate your chance to succeed or fail every time.  The latter is not conducive to a fun game in our opinion.

I hope that makes sense.

P.S. I just realised that Walterros is saying that the sheet IS picking up on advances for some rolls and not others, this is not as intended as the code should present the characteristic uniformly among all rolls that rely on the characteristic.  I've rewritten the DH2e sheet with a number of improvements and I'm happy to submit a pull request to fix this.

**Comment by RhOmicron** [comment] 2017-01-12 02:14
I figured out the experience thing from reading the rules. If I were to finish my version of the sheet (I even merged some of your things apart from the degrees of success). Would you then have a go at it and test it?

**Comment by Walterros** [comment] 2017-01-12 18:27
Yeah, the issue is some rolls are taking the drop down menu into account and some aren't. If it was uniform and the drop down menu was just used to track +5,10,ect then it'd be fine and I'd just have them add the value in. But the chance to hit rolls for weapons do take the drop down menu into account.

**Comment by messiahcide** [comment] 2017-03-01 20:39
This issue should closed

**Comment by Craftomega** [comment] 2017-03-05 00:00
This issue has been resolved.

**Closed** 2018-07-31 16:08 UTC
