### ISSUE TITLE
[Warhammer Fantasy 2nd Edition] Skill Training

### ISSUE THREAD

**Issue by realitor** [Roll20/roll20-character-sheets#4099] opened 2018-08-25 10:55 UTC
Training Level of some skills are not displayed after update to 2.0. Calculation of total roll is still correct.

Related skills: Charm, Concealment, Ride, Silent Move, Dodge Blow, Pick Lock, Shadowing, Sleight of Hand

**Comment by Anduh** [comment] 2018-08-25 13:48
Ping the author or some active editor of the sheet if you want this noticed. Few sheet authors scan the Issue section frequently.

**Comment by Almos80** [comment] 2018-08-27 10:33
I have no idea what this issue is referring to. I'm not seeing a problem in the code or on the sheet being displayed. This code hasn't changed since the update as far as I can see. I need an example of the problem so that I can see what the issue is.

**Comment by Almos80** [comment] 2018-08-27 11:17
I understand now, and I don't think this is something I can fix. The attribute **attr_Skill_Charm** has changed from **(@{Fellowship})** to **@{Fellowship}**. This was enough to change what is being displayed, but not enough to change the resulting calculation. Reverting to the old code would just create the same problem again, so I don't think this is advisable. I'll keep this in mind for future updates, but I do not intend to fix this current issue, because it would just recreate the problem for current users.

**Comment by nmbradley** [comment] 2021-12-10 19:38
This issue is now 3 years old and a resolution hasn't appeared during this time. I'm going to close this issue. If it's still a problem, creating a new issue might gather some fresh eyes.

**Closed by nmbradley** 2021-12-10 19:38 UTC
Labels: bug
