### ISSUE TITLE
Ryuutama failing to display images properly

### ISSUE THREAD

**Issue by NTWackowski** [Roll20/roll20-character-sheets#13207] opened 2024-08-15 02:44 UTC
My group noticed a couple months ago that a bunch of the images are failing to display on the character sheets, instead displaying a big "image not found" placeholder image. Especially noticeable on the GM character sheet, or in most of the chat boxes in roll20.

Some images still work properly, like the icons next to stats. Copied below are two examples, one which displays properly and one which doesn't:

```
<!-- Works -->
<img src="https://raw.githubusercontent.com/Roll20/roll20-character-sheets/master/Ryuutama/images/heart.png" alt="whiteheart" class="icon">

<!-- Doesn't work -->
<img class="logo" src="https://raw.githubusercontent.com/Roll20/roll20-character-sheets/master/Ryuutama/images/rtlogo.svg">
```

I'm not super familiar with HTML, but my best guess is that the issue comes from the not-working images being .svg files, while the working ones are all .png files. Is there any way the .svg's could be re-uploaded as .png's and the character sheet srcs updated to match?

The HTML file in question which needs updating: https://github.com/Roll20/roll20-character-sheets/blob/master/Ryuutama/Ryuutama.html#L591
One identified image not working: https://raw.githubusercontent.com/Roll20/roll20-character-sheets/master/Ryuutama/images/rtlogo.svg
Another image not working: https://raw.githubusercontent.com/Roll20/roll20-character-sheets/master/Ryuutama/images/gmCharacterSheetBanner.svg
They clearly display in the repository, but not when viewing the sheet in Roll20.

Attached are two images showing what I'm talking about, one working and one not.

![Displaying](https://github.com/user-attachments/assets/7a0dc083-2191-4747-8c57-d4ff340e86c5)
![NotDisplaying](https://github.com/user-attachments/assets/0e731497-ac9f-453a-b9cc-0d7f49366003)

**Comment by NorWhal** [comment] 2024-08-23 19:33
Thanks so much for letting us know about this! It took a bit of digging, but we found the cause and things look like they're back to normal on my end here. Closing this issue!

**Closed by NorWhal** 2024-08-23 19:33 UTC
Labels: bug, R20 reply
