### ISSUE TITLE
[D&D 5e OGL by Roll20] Ranger class issues

### ISSUE THREAD

**Issue by Operativ** [Roll20/roll20-character-sheets#5395] opened 2019-08-15 09:20 UTC
Hello,

the Ranger class has issues when creating a character via Charactermancer.

- Favored Enemy (Humanoid) fields display as blank after you type data in & move onto the next step. It saves properly though.
- At level 2, there's some "undefined spell list" under the level 1 spell list.
- at global attack modifier there's "undefined" or "[]" modifier without any description
- when choosing (at least) the Forest favored grounds, it says "undefined"

**Comment by clevett** [comment] 2019-10-03 15:51
Greetings,

I added these to our backlog and we'll take a look at them soon.

**Comment by nmbradley** [comment] 2021-03-30 05:15
Closing this ticket as I cannot reproduce these issues, and I believe that they have been resolved. If there are unresolved problems, please consider opening a new issue.

**Closed by nmbradley** 2021-03-30 05:15 UTC
Labels: R20 reply, bug
