### ISSUE TITLE
[Forbidden Lands] CharSheet Strength Attribute reverts to 0 / not adjustable

### ISSUE THREAD

**Issue by SpontEIN** [Roll20/roll20-character-sheets#13564] opened 2024-12-01 23:16 UTC
Hi,

the Forbidden Lands character sheet in roll20 (v1.9) reverts the Strength Attribute to 0 (zero) or is entirely not adjustable. This does only seem to affect Strength, not the other attributes or skills.

I haven't had these issues a week ago. Is it maybe connected to this recent commit: 9d8afd1c310929248985386281058b2e925d1810 (@vince-roll20)

Thx in advance

**Comment by vince-roll20** [comment] 2024-12-02 10:23
Hi SpontEIN,
Very sorry you are experiencing this issue. If there's a bug, I'm sure it was something I did with the last update, however I'm not seeing an issue with Strength in my testing.  Can you explain exactly how Strength is reverting to "0" and how you cannot adjust?  Also, is it only on the PC, Monster, or both?

**Comment by SpontEIN** [comment] 2024-12-02 10:39
Hi Vince, Thanks so much for your quick reply.

Improved bug description:
In newly created and also previously existing Character Sheets, under Character. I raise strength via the little arrow buttons to 4. The value 4 (to the right) and the 4 skulls flash up for a split second and are gone again. Displayed value is 0, no skulls.

When I change the Strength value in the Monster sheet e.g, to 5 it remains, the value in the Character sheet also changes to 5 and also remains.

Additionally, my group was experiencing the above described issues with other attributes (e.g. Wits). This occurred when multiple users were in the roll20 game at the same time (but not editing the same Character).

**Comment by SpontEIN** [comment] 2024-12-02 11:15
update: the above issue seems to only affect Character Sheets, that are shared/visible to "All Players" or where players have editing rights. I can not reproduce this bug for Characters, that are only visible/editable by me/GM

**Comment by vince-roll20** [comment] 2024-12-02 11:34
I think I found my bug regarding strength.  Since PC's cap at 6 (sheet actually allows 7 for reforged power users) and monsters cap at 48, I use the sheet's tab to jump between which strength_total should be used.  I was fixed one bug and basically introduced another accidentally.  Sheet should get updated Mon/Tue.  I'll see if I can reproduce the issue with other abilities, but the bug with strength shouldn't be related.

**Comment by erikbigrasqueens** [comment] 2024-12-02 15:58
Ran into this bug as well yesterday. The strength issue seems to be fixed in the beta game, but the strength score still seems to act as the cap for the other abilities (ie, other abilities can't be raised higher than the strength score - this was happening in our game too).

**Comment by vince-roll20** [comment] 2024-12-02 16:45
Thank you for the clarification.  I had no idea that was happening and I see it now.  I was strictly focusing on Strength.  I'll get that fixed.

**Comment by erikbigrasqueens** [comment] 2024-12-02 18:09
Both issues looks good to me now in the beta game.

Though, I noticed that the Agility, Wits and Empathy on the Monster sheet and the Character sheet get set to the same value, as if both sheets are using the same attribute variables. Wasn't looking at that before since I didn't use the monster sheet in my game, but just noticed now in the beta game.

**Comment by vince-roll20** [comment] 2024-12-02 18:27
Strength is the only oddball between pc and monster.  The other abilities are the same.
Roll20 sheets all share the same code, so if a sheet is opened by multiple controlling players/gm at the same time, edits could be problematic. This more a roll20 design issue and there really isn't much that can be done on the sheet side of things.  Beacon sheets may have a solution to this but I haven't dug very deep into Beacon yet.

**Comment by erikbigrasqueens** [comment] 2024-12-02 18:28
Good to know, thanks. Appreciate the quick fix on the strength issue!

**Comment by SpontEIN** [comment] 2024-12-02 18:41
Hi, yes thanks so much for the speedy debugging @vince-roll20 

I also tested the beta game:
- the behavior of the Character sheets looks good and as expected
- however, the monster sheet seems to have a capping issue now :-)

Steps to reproduce:
- reload beta game
- open Char Sheet (e.g. Ugug Peslu) 
- on Character Sheet set Strength to 2
- on Monster sheet, try to raise either Agility, Wits or Empathy above value 2
- Value of these Attributes resets to 2

**Comment by vince-roll20** [comment] 2024-12-02 23:26
Home from work now and I'm digging into it.  I appreciate the info.

**Comment by vince-roll20** [comment] 2024-12-03 03:17
I think I've straightened things out. beta game has been updated and this fix is included for tomorrows merge.

**Comment by SpontEIN** [comment] 2024-12-03 18:27
great work!
I tested all kinds of input combinations in the beta game and could NOT find any bug or faulty behavior! :partying_face: 
:+1:

**Comment by NorWhal** [comment] 2024-12-03 19:20
I've merged this fix, it's building now! Once someone has confirmed that the live sheet is working as expected, we can close out this issue.

**Comment by erikbigrasqueens** [comment] 2024-12-03 20:12
It looks to be working now on my end in a live sheet. Thanks!

**Comment by vince-roll20** [comment] 2024-12-03 22:55
Thanks for beta testing everyone. ;-P

**Comment by NorWhal** [comment] 2024-12-05 18:19
Wonderful! Closing this out!

**Closed by NorWhal** 2024-12-05 18:19 UTC
