### ISSUE TITLE
[ChroniquesOubliees] Sheet "Add" generates error on Roll20

### ISSUE THREAD

**Issue by Far2Casual** [Roll20/roll20-character-sheets#6252] opened 2020-04-22 09:27 UTC
Hello all,

If you try to add the "ChroniquesOubliees" sheet on a new game on roll20, the Sandbox will generate this error message.

`"SyntaxError: Invalid or unexpected token"
"SyntaxError: Invalid or unexpected token\n    at eval (<anonymous>)\n    at messageHandler (evalmachine.<anonymous>:284:6)\n    at process.<anonymous> (/home/node/d20-api-server/node_modules/tiny-worker/lib/worker.js:65:55)\n    at emitTwo (events.js:106:13)\n    at process.emit (events.js:194:7)\n    at process.nextTick (internal/child_process.js:766:12)\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)"`

The sheet is still working. Could someone help us find what "Invalid or unexpected toke" the roll20 platform is talking about ?

It has to be said that if you instead, import a "custom sheet" and you copy paste the code from this Github, no error is throw.

FYI @Ulty

**Comment by nmbradley** [comment] 2021-03-30 17:02
I'm not able to reproduce this, so I'm going to assume that this is fixed and close this issue. If you encounter this again, please create a new issue.

**Closed by nmbradley** 2021-03-30 17:02 UTC

**Comment by Ulty** [comment] 2021-03-30 19:47
Just create a new game and try to add the script COFantasy from the library. You get 

Your scripts are currently disabled due to an error that was detected. Please make appropriate changes to your script's code and click the "Save Script" button. We will then attempt to start running the scripts again. More info... If this script was installed from the Script Library, you might find help in the Community API Forum.

For reference, the error message generated was: SyntaxError: Invalid or unexpected token
