### ISSUE TITLE
Pathfinder 9th Attack

### ISSUE THREAD

**Issue by ronniehicks** [Roll20/roll20-character-sheets#3100] opened 2017-10-18 04:13 UTC
Style for the 9th attack seems to be messed up. See screenshot

![image](https://user-images.githubusercontent.com/1480609/31700690-b439a7ec-b390-11e7-83c3-7ccee54dfa1c.png)

**Comment by makupi** [comment] 2017-10-21 23:48
Which Pathfinder sheet are you refering to?

**Comment by ronniehicks** [comment] 2017-10-22 17:38
Standard Pathfinder

**Comment by plutosdad** [comment] 2017-11-14 15:19
we'll look at it

**Comment by vince-roll20** [comment] 2017-11-16 05:16
I'm not able to reproduce... 
In your image you have some extra rows after the 9th Attack,  ie Attack9: Damage9: Crit_confirm9:  Did you add that the macro-text?

**Comment by ronniehicks** [comment] 2018-01-26 21:56
Wow, sorry I took so long to get back to you, I didn't get notified of this. I'll double check, but I'm pretty certain that I'm just using the out-of-the-box multi-attack stuff in the sheet. I'll update here when I get a chance to test it again.

**Comment by ronniehicks** [comment] 2018-03-07 01:28
See below for the macro text in from the character sheet. Let me know if you want more than just this macro.

```js
{{attack9=[[ 1d20cs>[[ @{crit-target} ]] + [[ @{attack_macro} + @{iterative_attack9_value} ]] [iterative] ]]}} {{damage9=[[ @{damage-dice-num}d@{damage-die} + @{damage_macro} ]]}} {{crit_confirm8=[[ 1d20 + [[ @{attack_macro} + @{iterative_attack9_value} ]] [iterative] + [[ @{crit_conf_mod} ]] ]]}} {{crit_damage9=[[ [[ @{damage-dice-num} * [[ @{crit-multiplier} - 1 ]] ]]d@{damage-die} + ((@{damage_macro}) * [[ @{crit-multiplier} - 1 ]]) ]]}} {{precision_dmg91=@{precision_dmg_macro}}} {{precision_dmg92=@{global_precision_dmg_macro}}} {{critical_dmg91=@{critical_dmg_macro}}} {{critical_dmg92=@{global_critical_dmg_macro}}} {{attack9name=@{iterative_attack9_name}}}```

**Comment by vince-roll20** [comment] 2018-03-07 06:28
Try substituting your macro-text with
```{{attack9=[[ 1d20cs>[[ @{crit-target} ]] + [[ @{attack_macro} + @{iterative_attack9_value} ]] [iterative] ]]}} {{damage9=[[ @{damage-dice-num}d@{damage-die} + @{damage_macro} ]]}} {{crit_confirm9=[[ 1d20 + [[ @{attack_macro} + @{iterative_attack9_value} ]] [iterative] + [[ @{crit_conf_mod} ]] ]]}} {{crit_damage9=[[ [[ @{damage-dice-num} * [[ @{crit-multiplier} - 1 ]] ]]d@{damage-die} + ((@{damage_macro}) * [[ @{crit-multiplier} - 1 ]]) ]]}} {{precision_dmg91=@{precision_dmg_macro}}} {{precision_dmg92=@{global_precision_dmg_macro}}} {{critical_dmg91=@{critical_dmg_macro}}} {{critical_dmg92=@{global_critical_dmg_macro}}} {{attack9name=@{iterative_attack9_name}}}```

**Comment by ronniehicks** [comment] 2018-03-21 02:15
No dice. Took the exact macro from your response and I'm still getting the same issue, unfortunately. Let me know if you'd like to see the issue in action.

**Comment by vince-roll20** [comment] 2018-03-21 15:54
Hmmm.  Can you try resetting all the iterative macros?  Unless you have manually edited them, resetting(deleting them and letting the sheet re-populate with the default) will not change anything.

**Comment by clevett** [comment] 2018-07-31 19:49
Hello,

I'm working to close out the old issues in Github. Can anyone here let me know if this remains an issue? 

Thanks,
Cassie

**Comment by vince-roll20** [comment] 2018-07-31 21:45
This something that I personally could not reproduce...
Thanks Cassie

**Comment by clevett** [comment] 2018-07-31 22:00
Thanks for the update. I'm going to close this issue for now given its age. If it is something we need to open again just let me know.
-Cassie

**Closed by clevett** 2018-07-31 22:00 UTC

**Comment by ronniehicks** [comment] 2018-09-06 03:15
Looks like it's still happening for me 
![image](https://user-images.githubusercontent.com/1480609/45133097-312c6980-b159-11e8-8b72-75b6b0920916.png)

**Comment by vince-roll20** [comment] 2018-09-06 05:02
Thanks Ronnie.  You're welcome to [import ](https://wiki.roll20.net/My_Vault#Importing_Characters)your character to the [PF Community beta game](https://app.roll20.net/join/801350/kEQ72w) and I'll see if I can determine the cause.

**Comment by vince-roll20** [comment] 2018-09-11 06:37
I have to assign permissions for the imported characters.  You have control now.  And, I found the issue in the roll template.  We had code from the regular template's 9th attack  being used for the simple template output as well.   I'll submit a fix for next week.  Thank you for helping.  ;-)
 
![capture](https://user-images.githubusercontent.com/10321187/45342305-61f21180-b552-11e8-8235-7ea71eee0f24.png)
