### ISSUE TITLE
[DSA 4.1 - Roll20] Rounding Error

### ISSUE THREAD

**Issue by Necrask** [Roll20/roll20-character-sheets#8381] opened 2021-02-27 21:33 UTC
Hello,

I have the following problem:
My automatically calculated values for Initiative and AT-Basic are rounded down instead of rounded up like stated in the corerules (2008).

My char has the following stats
![Falschberechnet](https://user-images.githubusercontent.com/67807029/109400845-51fd6080-794b-11eb-8e89-41901b53410b.png)

With AT-Basic=(MU+GE+KK)/5 it should be =6.6 and therefore 7 like stated on page 50 with the example Range-Basic of 7,6 rounded to 8 but it's 6.
Likewise for INI it's on the sheet 9.6 to 9 and not to 10.

I think there is a If X>0.6 roundup and not X=>0.5 (as stated on page 50, Step 8) somewhere in the code.

Best regards

**Comment by nmbradley** [comment] 2021-03-30 05:42
@kreuvf you're the most recent editor of the DSA 4.1 sheet. Are you able to look at and resolve this issue?

**Comment by kreuvf** [comment] 2021-03-30 06:05
@nmbradley: On it. Detailed answer following.

**Comment by kreuvf** [comment] 2021-03-30 07:54
@Necrask: This answer is a bit more difficult, but I hope that I can make things clear.

### Is it a bug?
Yes and no. It is not a bug with regards to the calcuation:
```
'atbasis': Math.round(((+v.mu_basis + +v.ge_basis + +v.kk_basis) / 5) - wundeBauch - wundeRA - wundeLA - wundeRB - wundeLB),
'pabasis': Math.round(((+v.in_basis + +v.ge_basis + +v.kk_basis) / 5) - wundeBrust - wundeBauch - wundeRA - wundeLA - wundeRB - wundeLB),
'fkbasis': Math.round(((+v.in_basis + +v.ff_basis + +v.kk_basis) / 5) - wundeBrust - wundeBauch - wundeRA - wundeLA - wundeRB - wundeLB)
```
[Javascript's Math.round() rounds numbers >= .5 up.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round)

It is still a bug, because the user interface does not make clear what the "Mod" column is intended for. Things get worse considering that the official DSA 4.1 character sheet has exactly that column, but uses it differently.

In the official (paper) version the "Mod" column is only meaningful during character generation as this has direct influence on the starting max. value of each stat, i.e. strength with +2 means you can start with 16 instead of just 14.

The Roll20 character sheet uses the "Mod" column for bookkeeping of temporary changes to stats, i.e. due to wounds, illness or anything else that does not require a recalculation of derived stats (AT base, PA base, FK base etc. pp.). So, given this information the actual calculation is correct as it takes GE as 10: MU + GE + KK is 32, AT base gets calculated as 6.4 and is (correctly) rounded down to 6.

### What shall I do?
Use the "Basis" column for the real/"hard" value of each stat, so make Klugheit 12 and Gewandtheit 11 and you should be good for now.

### Will you fix it?
When I'm back home, I will add a [new issue referencing this one over at my fork of this repository](https://github.com/kreuvf/roll20-character-sheets/issues) (feel free to open one yourself in the meantime). Take a look around other issues and you will notice that there is no guarantee, when things will be implemented. I took over from previous developers and am steadily trying to make things better bit by bit, but this takes its time, so please be (very) patient.

**Comment by kreuvf** [comment] 2021-03-30 07:56
@nmbradley: You may leave this issue open, I will reference it in a commit when it's finally fixed, so it gets auto-closed on merge.

**Comment by Necrask** [comment] 2021-03-30 09:50
Thank you very much for the detailed explonation, I couldn't find that before opening a ticket so hopefully this will get others with the same issue the reason what should be done to bridge it.

Stay safe!

**Comment by nmbradley** [comment] 2021-03-30 14:28
This is a great answer, thank you for taking the time!

**Comment by kreuvf** [comment] 2024-06-09 17:30
Saw that this one is still open :blush: 

Will be fixed in an upcoming PR by informing the user about the use of the Mod column ("This column does not correspond to the column of the same name on the official paper character sheet, it is used to keep track of temporary changes from e. g. poison or illness which do not trigger a changes to derived values."):
![image](https://github.com/Roll20/roll20-character-sheets/assets/518136/8b32c14e-0452-4a47-bbfc-8720d9b3d902)

**Closed** 2024-06-11 18:35 UTC
Labels: being resolved
