### ISSUE TITLE
Issue with Shadowrun 5th Edition (Advanced) Sheet on the Technomancy Tab

### ISSUE THREAD

**Issue by Mikept18** [Roll20/roll20-character-sheets#11335] opened 2022-12-30 22:19 UTC
@Stexinator
Greetings, i hope everyone is having a good day and a happy new year
I am having issue getting access to The Technomancy tab, i have tried everything that can thick of but the technomancy tab shows the same as the magic and i don't know how to fix.
This Happened after the most resent update.

Hope to get a response soon.
Happy new Years!

![Capturar](https://user-images.githubusercontent.com/121696919/210131718-60ac0094-7059-4ae7-b108-da9101e94411.PNG)

**Comment by Stexinator** [comment] 2022-12-31 08:54
Hey @Mikept18 , unfortunately I could not figure out what went wrong. The original author merged magic and technomancy together and showed content through css selectors. Apparently something broke, when the navbar was reworked.

I fixed it now in #11337 by splitting the tabs earlier then I wanted. This should give back the functionality but might have some hiccups. If you find something else please report it :)

**Comment by Stexinator** [comment] 2022-12-31 08:57
As a workaround you could manipulate the html directly. Search for the css class technobound and chance display:none with display:block and magebound the other way around

**Comment by Mikept18** [comment] 2022-12-31 09:30
Thanks for the response man
i well do as you said and manipulate the Html

Much appreciated and happy new years

**Comment by Mikept18** [comment] 2022-12-31 09:50
as of now the issue seems to still persist unfortunately

**Comment by Mikept18** [comment] 2022-12-31 10:14
@Stexinator
Greetings again, i found something that might shine some light on might be going on
One of my players saved his Technomancer Char on the Vaults before the resent update and uploaded it back to the Game and this is what it showed

![Capturar2](https://user-images.githubusercontent.com/121696919/210132841-8042fce4-7fd4-4c8d-8a05-09d5c5083e3e.PNG)
![Capturar3](https://user-images.githubusercontent.com/121696919/210132905-367c4487-8a14-46e3-9a13-db43fa04babf.PNG)
Not sure if this helps pin point the issue but i still thought important to let you know.

**Comment by Stexinator** [comment] 2022-12-31 12:44
> as of now the issue seems to still persist unfortunately

Until Roll20 merges my fixes it will persist. I dont expect it to be on the live servers today. If you got a pro account I can send you the source files so that you can use custom character sheets

**Comment by Stexinator** [comment] 2022-12-31 12:50
> @Stexinator Greetings again, i found something that might shine some light on might be going on One of my players saved his Technomancer Char on the Vaults before the resent update and uploaded it back to the Game and this is what it showed
> 
> ![Capturar2](https://user-images.githubusercontent.com/121696919/210132841-8042fce4-7fd4-4c8d-8a05-09d5c5083e3e.PNG) ![Capturar3](https://user-images.githubusercontent.com/121696919/210132905-367c4487-8a14-46e3-9a13-db43fa04babf.PNG) Not sure if this helps pin point the issue but i still thought important to let you know.

Yeah, that gave a good hint. I changed from pseudo-checkbox to a real one. You could try to go into your char sheet attribute and search for istechnomancer. Change the value from "on" to "1" and see if that fixes it.

![grafik](https://user-images.githubusercontent.com/69796777/210137288-342ef0f9-8a7f-44b9-959c-1238cf69a9f2.png)


When my fixes go live it will need the "on", so you have to change it back

**Comment by Mikept18** [comment] 2022-12-31 13:04
@Stexinator It worked 
Thank you soo much man
Happy new years and keep up the good work! :) <3

**Comment by Stexinator** [comment] 2023-01-03 09:46
@Mikept18 the fix is live. Please check if it works as intended and close the issue if everything is okay

**Closed** 2023-01-03 13:27 UTC

**Comment by Mikept18** [comment] 2023-01-03 13:29
@Stexinator The fix works and i see no issues as of now
Again thanks for all the help and keep up the good work.
