### ISSUE TITLE
[Warhammer Fantasy 4th edition] Not written in the approved.yaml

### ISSUE THREAD

**Issue by MarcoPalmieri** [Roll20/roll20-character-sheets#4236] opened 2018-09-24 19:47 UTC
The character sheet for Warhammer Fantasy 4th Edition (WFRP4CharSheet) seems to be approved but it wasn't added in the approved.yaml.

**Comment by clevett** [comment] 2018-09-25 15:07
My apologies on that one. I'll get it added today.

**Comment by clevett** [comment] 2018-09-25 16:41
This was updated. Your sheet is now on live and showing up in the select.

**Comment by Birdominus** [comment] 2018-09-25 16:45
Perfect, Thank you!

**Comment by MarcoPalmieri** [comment] 2018-09-25 16:46
Perfect, thank you!

**Comment by MarcoPalmieri** [comment] 2018-09-25 17:13
it seems now that every campaign where i use that sheet doesn't load, tried different browser and asked other people to load those campaigns with the same result

**Comment by clevett** [comment] 2018-09-25 17:37
Hey Marco,

I am having the same problem. I bet the issue is the sheet.json does not have the correct name:

```
"css": "WFRP4Charsheet.css",
```

The files is actually named WFRP4Charsheet.CSS . Note the capitalized CSS on the end. Unix is likely interpreting this as being different than the one in the sheet.son.

@Arioch1973 Would you be interested in fixing this?

Thanks,
Cassie

**Comment by MarcoPalmieri** [comment] 2018-09-25 17:50
Thanks for your work! sadly i don't have the pro version but might take it just to use this sheet :V

**Comment by Arioch1973** [comment] 2018-09-26 09:48
Yeah, I tried to fix that yesterday. I put in for a file change and updating it. But GitHub complains about a merge conflict. Unfortunately I am completely new when it comes to dealing with GitHub, and I have been unsuccessful in fixing the issue.  I should have remembered that Linux is case sensitive, but I did not.  The file needs to be renamed immediately, and it also needs to be updated to the latest version.
Which it refused to do for me. Any help in resolving this would be much appreciated.

/Sincerely Johan/Arioch1973


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by clevett** [comment] 2018-10-02 16:44
Pull request 4266 fixed the issue. Thanks guys!

**Closed by clevett** 2018-10-02 16:44 UTC
