### ISSUE TITLE
[Dark Heresy 1st Edition] Dice Results Incorrect or Missing

### ISSUE THREAD

**Issue by RobbaYaga** [Roll20/roll20-character-sheets#7502] opened 2020-10-07 23:11 UTC
Occasionally,  when rolling dice, the system responds listing the roll as a failure when it is actually a success. This is shown in the screen shot where the character "Neo Castor Ajoku" makes a Logic Test. The target number was 65. The character rolls a 61 (which should be a success, but it is listed as a failure by 4.6 degrees

![image](https://user-images.githubusercontent.com/70450366/95396955-15fc2d00-08d0-11eb-9d56-b925b92135f6.png)

Additionally, other dice rolls are not shown (they can still be seen with a mouse-over) as shown is this screen shot where both of "Holt Winfrey" Inferno Pistol attacks do not show the dice roll.

![image](https://user-images.githubusercontent.com/70450366/95397272-c9652180-08d0-11eb-96ac-59b96bb3584d.png)

**Comment by Stexinator** [comment] 2020-10-08 08:16
@RobbaYaga can you reproduce the first screenshot consistently and provide the hover like in the second picture?

**Comment by Stexinator** [comment] 2020-10-08 13:17
Since I am not familiar with the first edition ruling I need some more clarification. In 2ed it is just the tenth digit that is regarded, when I looked at the roll-template the order of rounding was wrong for 2nd, so this might be the issue here.

    @RobbaYaga Correct me if I am wrong:

        Roll 10 Target 22 => 1 Degrees of Success (YES)
        Roll 20 Target 22 => 0 Degrees of Success (YES)
        Roll 10 Target 29 => 1 Degrees of Success (YES)
        Roll 19 Target 20 => 1 Degrees of Success (No, this would be 0 Degrees of Success like the second example above)
        Roll 19 Target 29 => 1 Degrees of Success (Yes)
        Roll 19 Target 19 => 0 Degrees of Success (No, this would be 1 Degrees of Success)
        Roll 10 Target 19 => 0 Degrees of Success (YES)
        Roll 20 Target 10 => 1 Degrees of Failure (YES)
        Roll 20 Target 19 => 1 Degrees of Failure (No, this would be 0 Degrees of Failure)
        Roll 29 Target 10 => 1 Degrees of Failure (YES)

In DH1e, "Degrees of Success" or "Degrees of Failure" really refers to Degrees of EXTRA Success or EXTRA Failure. If the roll is within 9 of the target, it is simply a success or failure. As soon as you have a difference of 10, it becomes an (extra) level of success or failure.

Difference of 0-9 = 0 levels of Success / Failure
Difference of 10-19 = 1 level of Success / Failure
Difference of 20-29 = 2 levels of Success / Failure
etc.

As stated before, the rounding issue is a problem because:
Successes are rounded down: Target of 50, roll of 38 = 1.2 levels of success which is rounded down to 1 level of success
Failures are rounded up: Target of 50, roll of 62 = 1.2 levels of failure which is rounded up to 1 level of failure.

The problem seems to be the negative values associated with calculating the difference between roll and target. If there is a way to take that difference, determine if it is a success or failure and then use an absolute value before rounding, it should solve the issue. I don't know JS however, so not sure how involved that is.

**Comment by Stexinator** [comment] 2020-10-08 13:36
I did some testing and fixing this is currently not possible. I let it sit for now and think about if reworking the template works might fix this.

**Comment by RobbaYaga** [comment] 2020-10-09 00:19
Here is another Logic roll from that character with the mouse-over. I'm not sure if this happens with other skills, I know it's happening with this skill and this it was easy to get it to reproduce.

![image](https://user-images.githubusercontent.com/70450366/95527506-7c05b480-09a3-11eb-80e1-4f4fd3ac2b42.png)

**Comment by Stexinator** [comment] 2020-10-09 10:36
The roll for logic uses scrunity for calculation and logic for display. Did you see this error also with other skills?

**Comment by RobbaYaga** [comment] 2020-10-09 15:22
I'm not absolutely certain. We've noticed this error a couple times, but I didn't record it happening then and so all instances may be Logic. If it happens again, I'll post a new issue.

Thank you so much for all your help!

**Comment by Stexinator** [comment] 2020-10-15 13:34
@RobbaYaga please close it when it is fixed

**Closed** 2020-10-15 18:50 UTC
