### ISSUE TITLE
[L5R Advanced] Incorrect insight value

### ISSUE THREAD

**Issue by Vyzzini** [Roll20/roll20-character-sheets#3719] opened 2018-05-01 20:16 UTC
The insight value calculated by the sheet ignores the ring values and only takes into account skills, courtier and etiquette bonuses and the extra insight field.
Tested on Safari 11.1 and Firefox 59.0.2

**Comment by Anduh** [comment] 2018-05-03 13:28
Tag the author in the issue, contact them in some other way or this might never be noticed in a timely fashion. Few of the many dozen sheet authors stalks the issue page to the extent that any relevant issues would be brought to their attention this way. Some authors have even a recommended way to contact them stated on sheet documentation.

**Comment by Vyzzini** [comment] 2018-07-31 20:52
Hello @clevett 

Yes, I still have this issue (I work around it using the manual insight adjustment so it's no big deal).

Vyzzini

**Comment by clevett** [comment] 2018-07-31 20:55
Hello @Vyzzini 

Thanks for the update. I pinged the sheet authors and we'll see if they are still around to reply.

**Comment by G-G-G** [comment] 2018-08-06 22:17
Hi @clevett I'm wondering why you tagged me in this trhead. I dont play this game and don't remember contributing to this discussion. Am i forgetting something?

**Comment by clevett** [comment] 2018-08-07 05:25
Oh sorry G-G-G. I looked through the commits for the L5R Advanced sheet and saw you had contributed to in April.

**Comment by G-G-G** [comment] 2018-08-07 07:36
Oh, I remember now. That was a very minor script fix that was asked for on the forums and I did to several sheets.

**Comment by clevett** [comment] 2018-08-07 13:45
@G-G-G Alright. Thanks for the update. :) No pressure to take on this task. I went through all the issues on GitHub and wanted to notify potential sheet authors who might be interested. Thanks!

**Comment by magosgrimely** [comment] 2018-12-07 06:47
Confirmed to be extant on Chrome Version 71.0.3578.80 (64-bit) and Firefox Version 63.0.3 (64-bit).

Resolution of this has been a bit muddied due to the fact that there are two L5R sheets 4e, and the code in question was written on the [other one](https://github.com/Roll20/roll20-character-sheets/blob/master/L5R/L5Rsheet.htm).

@RhOmicron seems to be the primary maintainer, though @rdefendi seems to have written the actual Insight calculation code. I've been taking a look but any actual debugging will require a Pro account.

**Comment by RhOmicron** [comment] 2018-12-07 06:53
I don't have a pro sub anymore and I'm away from home so I won't be able to implement a fix. I would have loved to.

People will have to make due with the additional insight window I added for repeating skills.

//RhOmicron

**Comment by magosgrimely** [comment] 2018-12-08 02:07
Would it be possible for you to create a separate PR with just the tag fixes that resolve the Insight calculation bug? Or do conflicts arise on merge with just those? If so, feel free to send me the diff, I'd gladly walk through resolving those.

**Comment by rdefendi** [comment] 2018-12-08 03:18
I intend to look at it. It might be super easy for you to incorporate, today was just a hell day at work so I didn't get lunch. I'll get it on my github and let you look at it.

**Comment by magosgrimely** [comment] 2018-12-08 05:36
The advanced sheet made no changes to the Insight code, at least none that I saw.

**Comment by magosgrimely** [comment] 2018-12-20 21:04
https://github.com/Roll20/roll20-character-sheets/commit/9926e141060bccad822a1507245b99659faa9d02#diff-0a7dd1fb539336fed0263c8feec2105c seems to have made things worse. Testing on both Firefox and Chrome showed that the Insight value now never updates, from any source.

**Comment by rdefendi** [comment] 2018-12-20 22:52
Yeah, the way github reconciles conflicts gives me hives. I introduced a typo after carefully testing all my code.

Here's a weird thing, though. This code worked two weeks ago. Now the exact same code, still saved with the same date, doesn't anymore. Same bug you have here. Very frustrating. It boils down to this:

If I put the insight code inside it's own script tags, it works. If I but ALL the sheet workers in a single set of script tags, it doesn't. So two sets of script tags...works. One set of script tags...broken.

Since this all started because someone changed to code because we're not allowed to have more than one set of script tags anymore, I'm not sure how to go forward. :( Other than to republish with the old bug to fix my typo form last week.

**Comment by magosgrimely** [comment] 2018-12-20 23:01
Does roll20 let you have a .js file at root that you can invoke from inside the htm?

**Comment by nmbradley** [comment] 2021-12-10 19:36
This issue is now 3 years old and a resolution hasn't appeared during this time. I'm going to close this issue. If it's still a problem, creating a new issue might gather some fresh eyes.

**Closed by nmbradley** 2021-12-10 19:36 UTC
Labels: request, help wanted
