### ISSUE TITLE
Shadowrun 5th Edition (Advanced) spirits and sprites disappeared

### ISSUE THREAD

**Issue by thesweetalpaca** [Roll20/roll20-character-sheets#10760] opened 2022-07-07 03:17 UTC
Someone has edited the sheet and in doing so, deleted necessary data that has completely set back my game. If someone is going to continue editing this sheet, please do so without erasing data or making it worse or breaking it, as so many of these edits tend to do. Currently every sprite/spirit that was recorded in every single sheet has vanished and that data is now lost.

**Comment by Stexinator** [comment] 2022-07-08 06:13
Fixed in #10764

If you think my changes make the sheet worse formulate it in a professional and objective way. Explain why it is worse, what did you like before the changes were made, how it impacts you and what are better alternatives

**Comment by thesweetalpaca** [comment] 2023-03-23 09:14
I disagree this should be closed. Alas I have no other option in my reply but to close it. @nmbradley  @mperes The updates continue to erase data, make the sheet worse, and do not match original aesthetic. I do not know who is to blame, as I never accused anyone in particular of being the source of such reckless changes. 

To this point, the previous complaint was voiced objectively (the complaint was that edits were made that deleted data and ruined games. That still stands and the only request was to not push edits that erased key data to multi-year long campaigns) and thus warranted no reply: key data was deleted during a needless edit. I explained how it impacted me: key data was deleted, setting back my game. I explained why it was worse: key data was deleted. The better alternative would be: do not push edits that delete data. In light of these suggestions that were already answered in the original post, the suggestion updates be sent to me in advance seemed facetious. The same issues continued after this post on a bimonthly basis.

Nearly every update replaces a pleasing aesthetic with one that no longer matches the original aesthetic and intent. Arrows that previously matched the aesthetic have been moved and changed to an inferior aesthetic and position. Strange needless additions to skills remain, such as a random add button under perception. It serves no purpose and still exists. The roll results have changed to exclude data from rolls about specialties, where specialties were previously indicated. Reaction buttons in combat cannot be resolved without tokens, and not every gm uses tokens in every skirmish. Similarly, when one person does not resolve combat via these various buttons of mismatched aesthetic and varying positions, they cannot send any other dice roll to chat without much clicking and refreshing, even if they resolved it without using said buttons. The aesthetic of totals has needlessly changed to look like an editable box replacing the unique box that clearly could not be edited. The fonts have been changed to an aesthetic that no longer fit the original sheet. 

There was no more professional way to request to not make frivolous edits, especially ones that delete data (as has happened many times in the past). But the edits that delete data have been the most difficult to compensate for. I have used this sheet for 7ish years. Sometimes the edits work. Routinely this sheet has been hacked apart and broken so as to be unusable (rolls not working, stats and edge broken, the sheet turning to nonsense code, broken fonts, broken lines, roll buttons failing or disappearing) and then barely cobbled together again a week or two later. Using this sheet is frequently a matter of crossing fingers and hoping no one ruins it any further. My intent is not to be harsh, but I close this topic under duress and expect to open another soon the next time something is broken, data is erased, or the original aesthetic is destroyed.  

Again, I do not know who is to blame for frivolous edits, so this is not a targeted response, merely a plea. Please stop making ugly, sheet breaking, data erasing, session ruining edits to the sheets. Please try to respect the original edit and refrain from pushing changes before they re ready.

**Comment by Stexinator** [comment] 2023-03-23 11:21
If you think that this issue is not resolved, dont close it. If this issue was not resolved, why didnt you respond since half a year?

Answering to your rant: You can blame me, since I am the one editing the sheet. I maintain it since 4 years. So all recent changes and bugfixes were done by me.
None of your other issues was ever reported to me. Everyone I talked about like the changes I did.

Which data was deleted? Whenever I moved an obsolete dataset to a new one I wrote a converter that was tested by multiple people and worked. If you had issues, why didnt you report them?
Sending you upcoming changes it not facetious, I only have so much testdata and if you run into issues repeatedly that others dont I think you should really give it a thought.

Aesthetics are discussable, but I am really intrigued by you claiming that I replaced arrows. The recent UI changes where replacing notes checkboxes with arrows. So please add screenshots or point me directly to where it happened. If it was not intentional I am happy to fix it.

If you cannot figure out what the "random" add button below perception is you could try it out. But since your tone is quite dismissive I guess it is rather that it does not match your aesthetic.

Roll results have changed? I didnt touch anything about that for over a year. If that was an issue, why didnt you report it?

Reaction buttons in combat cannot be resolved without tokens, and not every gm uses tokens in every skirmish. => That is true and no problem. The buttons are quite small, so I thought people will just ignore it. But I can add an option to hide it.

Similarly, when one person does not resolve combat via these various buttons of mismatched aesthetic and varying positions, => Varying positions? You mean like, when there are multiple buttons they space out equally below the roll? I guess I need to see some screenshots to get what you mean. 
they cannot send any other dice roll to chat without much clicking and refreshing, even if they resolved it without using said buttons. => That has nothing to do with the buttons. If this is happening to you or your fellow players you should open a help desk ticket

The aesthetic of totals has needlessly changed to look like an editable box replacing the unique box that clearly could not be edited. => Nothing I changed, Roll20 had a style update

The fonts have been changed to an aesthetic that no longer fit the original sheet. => Nothing I changed, Roll20 had a style update

There was no more professional way to request to not make frivolous edits, especially ones that delete data (as has happened many times in the past) => That is untrue. If you dont realise which tone and words you are using, you should reflect about it. Also I am intrigued how many times your data and which data was deleted. I think there might be your main problem. You are upset about something, that most likely has nothing to do with the sheet edits.

Routinely this sheet has been hacked apart and broken so as to be unusable (rolls not working, stats and edge broken, the sheet turning to nonsense code, broken fonts, broken lines, roll buttons failing or disappearing) and then barely cobbled together again a week or two later. => This sounds like a browser issue. Which browser are you using? Neither me nor my playgroup or any playgroup I talked to had such an issue since more then 2 years. As far as I remembered it happend once and was fixed the next day.

Using this sheet is frequently a matter of crossing fingers and hoping no one ruins it any further. => If you have a paid roll20 account you can decouple your game from the automatic updates. Then this would be no problem for you.

expect to open another soon the next time something is broken, data is erased, or the original aesthetic is destroyed => Please do so, that is way to work with git issues. One issue per problem you encounter


Again, I do not know who is to blame for frivolous edits, so this is not a targeted response, merely a plea. Please stop making ugly, sheet breaking, data erasing, session ruining edits to the sheets. Please try to respect the original edit and refrain from pushing changes before they're ready. => So what is happening since several years?

I cannot follow your line of thinking. The whole way you phrase your complaint is to say that someone is making everything worse on purpose. If you can not handle change, that is a problem that you got and Roll20 provides way to circumvent it.

**Comment by nmbradley** [comment] 2023-03-27 21:51
Hey folks, 

I am going to close this conversation, to allow you both to step back from it and comport yourselves. 

I will say to both of you, in general, to remind yourselves of the human on the other side of the screen; nobody is here with bad intentions. Also, to remember that a lot can be lost through the medium of text, particularly via a service that is used by people of multiple different nationalities and levels of proficiency with written English.

@thesweetalpaca while I acknowledge it can certainly be frustrating to have a sheet change and erase data, it is worth bearing in mind that the work that 95% of sheet development is unpaid and difficult work, enacted purely for the love of the community and the game the individual developer is trying to support. I have the utmost faith that these changes were not made maliciously.

I also acknowledge that it can be difficult for non-technical people to know precisely what information to provide when encountering issues like this; but I can say with considerable experience that the information you provided in your original post would not have been enough for Stexinator to identify the issue you were experiencing. I see the initial response to be a good faith, albeit blunt, attempt to engage with you and diagnose the root cause of the issue.

Furthermore, I have absolutely no doubt that Stexinator would delight having additional assistance and guidance on the direction of this sheet. The sheet repository is intended to be a community endeavor; you will arrive at a better sheet if you cooperate and communicate.

To that end, once you have both had a chance to cool off, please re-post this issue and provide as clear, detailed, and objective data and feedback as you can manage. Illustrate with examples of how the issue can cause problems. Screenshots are worth a thousand words in this regard, and they're pretty easy to copy and paste into a github issue. Make several issues if there are several points to be made; that's what they're there for.

@Stexinator I trust you will be open to politely discussing Alpaca's concerns, and we can go from there.

I promise you that if the two of you cooperate in this way, you will end up with a sheet that you are both more satisfied with.

**Closed by nmbradley** 2023-03-27 21:51 UTC
