### ISSUE TITLE
[Apocalypse World 2nd Edition] possible to display dice results in move results?

### ISSUE THREAD

**Issue by JRandall0308** [Roll20/roll20-character-sheets#5956] opened 2020-03-16 21:22 UTC
https://github.com/Roll20/roll20-character-sheets/tree/master/AW2E

Would it be possible to display the dice results in the move results? So instead of simply seeing something like "Weird 9, Partial Success" you'd see "Weird [3]+[4]+2 = 9, Partial Success".

I know that functionally these are identical, but the old school gamer in me likes to see the individual dice results. Even if they are irrelevant.

**Comment by Anduh** [comment] 2020-03-16 21:39
What is the full name of "AW2E"?

**Comment by JRandall0308** [comment] 2020-03-17 00:38
https://github.com/Roll20/roll20-character-sheets/tree/master/AW2E
Apocalypse World 2nd Edition
(Sorry, not sure how this got dumped in the general area instead of that specific sheet.)

**Comment by Anduh** [comment] 2020-03-17 10:48
I'd edit the title to include the full name of the game for clarity & visibilty

**Comment by BlckKnght** [comment] 2020-03-20 23:15
Can't you see the values for the individual dice if you mouse over the 9 to see the tooltip? I'm currently trying to go the other direction on the sheet for The Sprawl, which shows individual dice without adding them up. That's *really* annoying, as at least twice a session somebody does the math wrong in their head and thinks something different occurred than everybody else.

**Comment by Stexinator** [comment] 2021-02-25 19:51
@JRandall0308  if this is resolved, please close it

**Comment by JRandall0308** [comment] 2021-03-12 14:28
@Stexinator Nope... individual dice rolls are still not broken out. It's not a big deal since you can build your own macro, just a bit of a disappointment on an otherwise good character sheet.
![image](https://user-images.githubusercontent.com/30268855/110953324-3879f280-8315-11eb-8867-c9df3321bf40.png)

**Comment by nmbradley** [comment] 2021-03-30 17:28
@JRandall0308 are you able to share the macro you have created to aid in a solution?

**Comment by JRandall0308** [comment] 2021-04-06 13:09
> @JRandall0308 are you able to share the macro you have created to aid in a solution?

Sure! These are specific to my character but should give you the idea.

I didn't do anything fancy where the macro would pull the ability modifier from the character sheet. I simply hard-coded the values (+1 Cool, +3 Weird, etc.). Note that this is a very built up character (Brainer) who has taken moves from multiple other playbooks.

AUF /roll 2d6+1 Act Under Fire (Cool)

CBR /roll 2d6+3 Casual Brain Receptivity (Weird substituted for Sharp in Read a Person) - victim must be able to see you, but you don't have to interact

Healing /roll 2d6+3 Healing Touch (Weird) - refbook p. 5

Mothers /roll 2d6+3 The Mother's Heartbeat (Weird) // When you withdraw into the world's psychic maelstrom... (Child-Thing)
Open /roll 2d6+3 Open Your Brain (Weird)

Puppet /roll 2d6+3 In-Brain Puppet Strings (Weird)

Seduce /roll 2d6+2 Seduce, Manipulate, Fast-Talk, Lie (Hot)

Help /roll 2d6+3 Seeing Souls (Weird instead of Hx when you Help or Interfere) - refbook p. 19

Sitch /roll 2d6+0 Read a Sitch (Sharp) // and can ask an extra question via Sniffing the Air (Child-Thing)

Whisper /roll 2d6+3 Direct-Brain Whisper Projection (Weird instead of Hard for Go Aggro) - victim has to be able to see you but you don't have to interact; if victim forces your hand, your mind counts as a weapon (2-harm, AP, close, loud-optional)

---

And an example of the output...

![image](https://user-images.githubusercontent.com/30268855/113715656-c00a1580-96b7-11eb-89d3-4ec119b7e3af.png)

**Comment by nmbradley** [comment] 2021-12-10 20:06
This seems to me like it is a difference of opinion, and not a case of the sheet not working as intended. Results can be seen on any dice roll by hovering them with the cursor, and these macros can be employed if a different behavior is desired. Closing this issue, but if there's some larger problem I'm not seeing, please feel free to recreate it.

**Closed by nmbradley** 2021-12-10 20:06 UTC
Labels: request
